export type Role='OWNER'|'ADMIN'|'EDITOR'|'OPERATOR'|'VIEWER';
export type Platform='FACEBOOK'|'INSTAGRAM'|'THREADS'|'TIKTOK';
export type PublishMode='API'|'BROWSER'|'HYBRID';
export type ContentType='VIDEO'|'IMAGE'|'TEXT';
export type JobStatus='QUEUED'|'PROCESSING'|'RETRYING'|'PUBLISHED'|'FAILED'|'CANCELLED';
export interface User{id:string;email:string;passwordHash:string;status:'ACTIVE'|'DISABLED'}
export interface Workspace{id:string;name:string}
export interface WorkspaceMember{workspaceId:string;userId:string;role:Role}
export interface Brand{id:string;workspaceId:string;name:string;slug:string;language:string;timezone:string;currency:string;status:'ACTIVE'|'ARCHIVED'}
export interface Product{id:string;brandId:string;name:string;slug:string;description?:string;imageAssetId?:string;supplierUrl?:string;landingUrl?:string;cost?:string;sellingPrice?:string;currency:string;status:'DRAFT'|'ACTIVE'|'ARCHIVED'}
export interface MediaAsset{id:string;brandId:string;workspaceId:string;type:'VIDEO'|'IMAGE';storageKey:string;mimeType:string;sizeBytes?:number;width?:number;height?:number;durationMs?:number}
export interface ContentItem{id:string;brandId:string;productId?:string;type:ContentType;title:string;hook?:string;body?:string;cta?:string;masterAssetId?:string;status:'DRAFT'|'READY'|'ARCHIVED'}
export interface ContentVariant{id:string;contentItemId:string;socialAccountId?:string;platform:Platform;caption?:string;body?:string;hashtags:string[];cta?:string;assetId?:string;status:'DRAFT'|'READY'}
export interface Campaign{id:string;brandId:string;productId?:string;name:string;description?:string;status:'DRAFT'|'ACTIVE'|'PAUSED'|'COMPLETED';startAt?:string;endAt?:string;contentIds:string[]}
export interface AuthSession{id:string;userId:string;refreshTokenHash:string;expiresAt:number;revokedAt?:number}
export interface AuditLog{id:string;workspaceId:string;userId?:string;action:string;entityType:string;entityId?:string;metadata?:Record<string,unknown>;createdAt:number}
export interface SocialAccount{id:string;brandId:string;platform:Platform;username?:string;displayName?:string;platformAccountId?:string;publishMode:PublishMode;status:'CONNECTED'|'EXPIRED'|'DISCONNECTED'|'ERROR';browserProfileId?:string}
export interface EncryptedCredential{id:string;socialAccountId:string;provider:string;ciphertext:string;iv:string;authTag:string;refreshCiphertext?:string;expiresAt?:number;scopes?:string[]}
export interface BrowserNode{id:string;workspaceId:string;name:string;host:string;port:number;status:'ONLINE'|'OFFLINE'|'DEGRADED';provider:'GPMLOGIN';lastSeenAt?:number;maxConcurrency:number;encryptedNodeKey?:string}
export interface BrowserProfile{id:string;brandId:string;browserNodeId:string;provider:'GPMLOGIN';providerProfileId:string;name:string;status:'READY'|'RUNNING'|'STOPPED'|'ERROR';metadata?:Record<string,unknown>;socialAccountId?:string}
export interface BrowserRegistration{nodeId:string;tokenHash:string;expiresAt:number;consumedAt?:number}
export type PublishStrategy='API'|'BROWSER';
export interface PublishBatch{id:string;brandId:string;contentItemId:string;createdBy:string;createdAt:number}
export interface PublishJob{id:string;batchId:string;brandId:string;socialAccountId:string;contentVariantId:string;platform:Platform;strategy:PublishStrategy;scheduledAt:number;status:JobStatus;attemptCount:number;maxAttempts:number;idempotencyKey:string;remoteCorrelationId?:string;errorCode?:string;errorMessage?:string}
export interface PublishAttempt{id:string;publishJobId:string;attemptNumber:number;strategy:PublishStrategy;startedAt:number;finishedAt?:number;status:string;errorType?:string;errorCode?:string;errorMessage?:string;metadata?:Record<string,unknown>}
export interface PublishedPost{id:string;brandId:string;publishJobId:string;socialAccountId:string;contentVariantId:string;platform:Platform;platformPostId:string;platformPostUrl?:string;publishedAt:number}
export interface PostMetric{id:string;publishedPostId:string;capturedAt:number;captureKey:string;views?:number;likes?:number;comments?:number;shares?:number;saves?:number;clicks?:number;rawMetrics?:Record<string,unknown>}
export interface TrackedLink{id:string;brandId:string;productId?:string;contentItemId?:string;publishedPostId?:string;code:string;targetUrl:string;utmSource?:string;utmMedium?:string;utmCampaign?:string;utmContent?:string}
export interface ClickEvent{id:string;trackedLinkId:string;timestamp:number;referrer?:string;userAgent?:string;country?:string;deviceType?:string}
